language: cpp
compiler: gcc

# Handle git submodules yourself

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

# Specify the compiler version
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake .. && make -j12 && ctest -j12