language: cpp
compiler: gcc

dist: xenial

# Handle git submodules yourself

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - boost1.65

# Specify the compiler version
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - eval "${MATRIX_EVAL}"
    - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake .. -DCOVERALLS=ON && make -j12 && ctest -j12

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'